<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.6 on darwin)" generated="20201104 23:40:26.354" rpa="false">
<suite id="s1" name="Socket Send Message" source="/Users/leo/Documents/codes/texugo/tests/functional_tests/tests/socket_send_message.robot">
<test id="s1-t1" name="Running Texugo Docker Image">
<kw name="Run Texugo" library="Texugo">
<status status="PASS" starttime="20201104 23:40:26.452" endtime="20201104 23:40:26.628"></status>
</kw>
<kw name="Verify Message" library="SocketInjector">
<arguments>
<arg>${port1}</arg>
<arg>${port2}</arg>
<arg>${message}</arg>
<arg>${destination}</arg>
</arguments>
<assign>
<var>${result}</var>
</assign>
<msg timestamp="20201104 23:40:26.630" level="FAIL">ConnectionRefusedError: [Errno 61] Connection refused</msg>
<status status="FAIL" starttime="20201104 23:40:26.628" endtime="20201104 23:40:26.630"></status>
</kw>
<timeout value="1 minute"></timeout>
<status status="FAIL" starttime="20201104 23:40:26.451" endtime="20201104 23:40:26.630" critical="yes">ConnectionRefusedError: [Errno 61] Connection refused</status>
</test>
<doc>
Testing Texugo Sockets Connection
</doc>
<status status="FAIL" starttime="20201104 23:40:26.355" endtime="20201104 23:40:26.631"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Socket Send Message">Socket Send Message</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
